version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./shipay:/app/shipay/
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: "shipay"
        POSTGRES_USER: "shipay"
        POSTGRES_DB: "shipay"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
